version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maven"
      - "dependencies"
    ignore:
      # Ignore Mockito 5.X.X as it does not support Java 8
      - dependency-name: "org.mockito:mockito-*"
        update-types: ["version-update:semver-major"]