name: Update version in a Java project
description: Updates version numbers in specified files

inputs:
  release_version:
    description: Version number to update to
    required: true
  current_version:
    description: Version number to update from
    required: true
  files:
    description: Comma seperated list of file paths to search
    required: true

runs:
  using: "composite"
  steps:
    - id: Thing
      name: Thing
      run: version.sh
      shell: bash
      working-directory: ${{ env.GITHUB_WORKSPACE }}
      env:
        files: ${{ inputs.files }}