name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code from GitHub
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
      - id: normalize-version
        name: Normalize Version Number
        run: echo "VERSION=$(echo ${{ inputs.release_version }} | sed 's/v//')" >> $GITHUB_ENV

      - id: set-version
        name: Set current release version env variable
        run: echo "CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - id: change-version
        name: Version code with release version
        uses: ./.github/actions/update-version
        env:
          current_version: ${{ env.CURRENT_VERSION }}
          release_version: ${{ inputs.release_version }}
        with:
          release_version: ${{ inputs.release_version }}
          current_version: ${{ env.current_version }}
          files: "mkdocs.yml,pom.xml,**/*pom.xml,README.md"

      - id:  upload-artifact
        name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: workspace
          path: .

  build:
    runs-on: ubuntu-latest
    needs: update-version
    strategy:
      max-parallel: 5
      matrix:
        java: [8, 11, 15, 16, 17, 18, 19, 20 ]
    steps:
      - id: download-artifact
        name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: workspace

      - id: setup-java 
        name: Setup java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          distribution: "corretto"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - id: build-with-maven
        name: Build with Maven
        run: mvn -B install --file pom.xml