name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
      create_release:
        description: 'Push release to Maven Central?'
        type: boolean
        default: false
        required: false

env:
  RELEASE_COMMIT: ${{ github.sha }}

permissions:
  id-token: write
  contents: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout code from GitHub
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
      
      - id: normalize-version
        name: Normalize Version Number
        run: echo "VERSION=$(echo ${{ inputs.release_version }} | sed 's/v//')" >> $GITHUB_ENV

      - id: set-version
        name: Set current release version env variable
        run: echo "CURRENT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - id: change-version
        name: Version code with release version
        uses: ./.github/actions/update-version
        env:
          current_version: ${{ env.CURRENT_VERSION }}
          release_version: ${{ inputs.release_version }}
        with:
          release_version: ${{ inputs.release_version }}
          current_version: ${{ env.current_version }}
          files: "./mkdocs.yml,pom.xml,./README.md"

      - id: status
        name: Show git status
        run: git status

      - id:  upload-artifact
        name: Upload artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: workspace
          path: .

  build:
    runs-on: ubuntu-latest
    needs: update-version
    strategy:
      max-parallel: 5
      matrix:
        java: [8, 11, 15, 16, 17, 18, 19, 20 ]
    steps:
      - id: download-artifact
        name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: workspace

      - id: setup-java 
        name: Setup java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          distribution: "corretto"
          java-version: ${{ matrix.java }}
          cache: "maven"

      - id: build-with-maven
        name: Build with Maven
        run: mvn -B install --file pom.xml

  publish:
    runs-on: ubuntu-latest
    environment: Release
    needs: build
    steps:
      - id: download-artifact
        name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: workspace

      - id: setup-java 
        name: Setup java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2
        with:
          distribution: 'zulu'
          java-version: 8
          server-id: ossrh
          server-username: MAVEN_USERNAME # env var name
          server-password: MAVEN_PASSWORD # env var pass
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - id: build-and-release-with-maven
        if: ${{ inputs.create_release == 'true' }}
        name: Build with Maven
        run: mvn -Prelease clean deploy -DskipTests
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  create_tag:
    needs: publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - id: download-artifact
        name: Download artifact
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a
        with:
          name: workspace

      - id: setup-git
        name: Git client setup and refresh tip
        run: |
          git config user.name "Powertools for AWS Lambda (Java) bot"
          git config user.email "aws-lambda-powertools-feedback@amazon.com"
          git config remote.origin.url >&-
            
      - id: status
        name: Show git status
        run: git status

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     limit-access-to-actor: true

      - name: Create Git Tag
        run: |
          git commit -am "chore: version bump"
          git tag -a v"${RELEASE_VERSION}" -m "release_version: v${RELEASE_VERSION}"
          git push origin v"${RELEASE_VERSION}"
        env:
          RELEASE_VERSION: ${{ inputs.release_version }}